module prime_core (


);






////////////////////////////////////////////////////////////////
// Interconnect
////////////////////////////////////////////////////////////////
amba_axi_m2s2 u_interconnect_0 
      #(	 
       .ADDR_BASE0(32'b00000000),  // Slave-0
       .ADDR_BASE1(32'b10000000),  // Slave-1
       )
(
     .ARESETn         	(		),
     .ACLK            	(		),
                      	(		),
     .M0_AWID         	(		),
     .M0_AWADDR       	(		),
     .M0_AWLEN        	(		),
     .M0_AWLOCK       	(		),
     .M0_AWSIZE       	(		),
     .M0_AWBURST      	(		),
     .M0_AWPROT       	(		),
     .M0_AWVALID      	(		),
     .M0_AWREADY      	(		),
     .M0_AWQOS        	(		),
     .M0_AWREGION     	(		),
     .M0_WDATA        	(		),
     .M0_WSTRB        	(		),
     .M0_WLAST        	(		),
     .M0_WVALID       	(		),
     .M0_WREADY       	(		),
     .M0_BID          	(		),
     .M0_BRESP        	(		),
     .M0_BVALID       	(		),
     .M0_BREADY       	(		),
     .M0_ARID         	(		),
     .M0_ARADDR       	(		),
     .M0_ARLEN        	(		),
     .M0_ARLOCK       	(		),
     .M0_ARSIZE       	(		),
     .M0_ARBURST      	(		),
     .M0_ARPROT       	(		),
     .M0_ARVALID      	(		),
     .M0_ARREADY      	(		),
     .M0_ARQOS        	(		),
     .M0_ARREGION     	(		),
     .M0_RID          	(		),
     .M0_RDATA        	(		),
     .M0_RRESP        	(		),
     .M0_RLAST        	(		),
     .M0_RVALID       	(		),
     .M0_RREADY       	(		),
                      	(		),
     .M1_AWID         	(		),
     .M1_AWADDR       	(		),
     .M1_AWLEN        	(		),
     .M1_AWLOCK       	(		),
     .M1_AWSIZE       	(		),
     .M1_AWBURST      	(		),
     .M1_AWPROT       	(		),
     .M1_AWVALID      	(		),
     .M1_AWREADY      	(		),
     .M1_AWQOS        	(		),
     .M1_AWREGION     	(		),
     .M1_WDATA        	(		),
     .M1_WSTRB        	(		),
     .M1_WLAST        	(		),
     .M1_WVALID       	(		),
     .M1_WREADY       	(		),
     .M1_BID          	(		),
     .M1_BRESP        	(		),
     .M1_BVALID       	(		),
     .M1_BREADY       	(		),
     .M1_ARID         	(		),
     .M1_ARADDR       	(		),
     .M1_ARLEN        	(		),
     .M1_ARLOCK       	(		),
     .M1_ARSIZE       	(		),
     .M1_ARBURST      	(		),
     .M1_ARPROT       	(		),
     .M1_ARVALID      	(		),
     .M1_ARREADY      	(		),
     .M1_ARQOS        	(		),
     .M1_ARREGION     	(		),
     .M1_RID          	(		),
     .M1_RDATA        	(		),
     .M1_RRESP        	(		),
     .M1_RLAST        	(		),
     .M1_RVALID       	(		),
     .M1_RREADY       	(		),
                      	(		),
     .S0_AWID         	(		),
     .S0_AWADDR       	(		),
     .S0_AWLEN        	(		),
     .S0_AWLOCK       	(		),
     .S0_AWSIZE       	(		),
     .S0_AWBURST      	(		),
     .S0_AWPROT       	(		),
     .S0_AWVALID      	(		),
     .S0_AWREADY      	(		),
     .S0_AWQOS        	(		),
     .S0_AWREGION     	(		),
     .S0_WDATA        	(		),
     .S0_WSTRB        	(		),
     .S0_WLAST        	(		),
     .S0_WVALID       	(		),
     .S0_WREADY       	(		),
     .S0_BID          	(		),
     .S0_BRESP        	(		),
     .S0_BVALID       	(		),
     .S0_BREADY       	(		),
     .S0_ARID         	(		),
     .S0_ARADDR       	(		),
     .S0_ARLEN        	(		),
     .S0_ARLOCK       	(		),
     .S0_ARSIZE       	(		),
     .S0_ARBURST      	(		),
     .S0_ARPROT       	(		),
     .S0_ARVALID      	(		),
     .S0_ARREADY      	(		),
     .S0_ARQOS        	(		),
     .S0_ARREGION     	(		),
     .S0_RID          	(		),
     .S0_RDATA        	(		),
     .S0_RRESP        	(		),
     .S0_RLAST        	(		),
     .S0_RVALID       	(		),
     .S0_RREADY       	(		),
                      	(		),
     .S1_AWID         	(		),
     .S1_AWADDR       	(		),
     .S1_AWLEN        	(		),
     .S1_AWLOCK       	(		),
     .S1_AWSIZE       	(		),
     .S1_AWBURST      	(		),
     .S1_AWPROT       	(		),
     .S1_AWVALID      	(		),
     .S1_AWREADY      	(		),
     .S1_AWQOS        	(		),
     .S1_AWREGION     	(		),
     .S1_WDATA        	(		),
     .S1_WSTRB        	(		),
     .S1_WLAST        	(		),
     .S1_WVALID       	(		),
     .S1_WREADY       	(		),
     .S1_BID          	(		),
     .S1_BRESP        	(		),
     .S1_BVALID       	(		),
     .S1_BREADY       	(		),
     .S1_ARID         	(		),
     .S1_ARADDR       	(		),
     .S1_ARLEN        	(		),
     .S1_ARLOCK       	(		),
     .S1_ARSIZE       	(		),
     .S1_ARBURST      	(		),
     .S1_ARPROT       	(		),
     .S1_ARVALID      	(		),
     .S1_ARREADY      	(		),
     .S1_ARQOS        	(		),
     .S1_ARREGION     	(		),
     .S1_RID          	(		),
     .S1_RDATA        	(		),
     .S1_RRESP        	(		),
     .S1_RLAST        	(		),
     .S1_RVALID       	(		),
     .S1_RREADY       	(		)
     
);


endmodule
